library(MASS)
rawdata=read.csv("Galapagos.csv",header = T)
attach(rawdata)
lnarea= log(Area)
lnelev=log(Elev)
logdistnear = log(DistNear) 
logareanear = log(AreaNear) 
detach(rawdata) 
glm_1 = glm(Native~logarea+logelev+logdistnear+logareanear, data = rawdata ,family= poisson("log")) 
summary(glm_1) 