library(TSA)
a=ARMAacf(0.8,-0.2,lag.max = 20)
jpeg('1a.jpg')
plot(a,type = "h")
dev.off()
b=ARMAacf(0.8,0.2,lag.max = 20)
jpeg('1b.jpg')
plot(b,type = "h")
dev.off()
c=ARMAacf(0.5,lag.max = 20)
jpeg('2a.jpg')
plot(c,type = "h")
dev.off()
d=ARMAacf(-0.5,lag.max = 20)
jpeg('2b.jpg')
plot(d,type = "h")
dev.off()
e=ARMAacf(0.95,lag.max = 20)
jpeg('2c.jpg')
plot(e,type = "h")
dev.off()
f=ARMAacf(0.25,lag.max = 20)
jpeg('2d.jpg')
plot(f,type = "h")
dev.off()
