library(TSA)
data(beersales)
plot(beersales)
year=seq(1975,1990,1)
jpeg("beersales2.jpg")
plot(beersales,type = "l")
for (n in 1:12) {
  m=seq(n,192,12)
  points(year,beersales[m],pch= n) 
  n=n+1
}
dev.off()
month.=season(beersales)
a=lm(beersales~month.-1)
summary(a)
jpeg("beersales3.jpg")
plot(y=rstudent(a),x= as.vector(time(beersales)), xlab='Time', ylab = 'Standardized Residuals', type = 'l')
points(y=rstudent(a), x = as.vector(time(beersales)),pch=as.vector(season(beersales)))
dev.off()
quad.model = lm(beersales~season(beersales)+time(beersales)+
                I(time(beersales)^2)-1) 
summary(quad.model)
jpeg("beersales4.jpg")
plot(y=rstudent(quad.model),x= as.vector(time(beersales)), xlab='Time', ylab = 'Standardized Residuals', type = 'l')
points(y=rstudent(quad.model), x = as.vector(time(beersales)),pch=as.vector(season(beersales)))
dev.off()
rstudent(quad.model)
runs(rstudent(quad.model))
jpeg("beersales5.jpg")
acf(rstudent(quad.model))
dev.off()
jpeg("beersales6.jpg")
hist(rstudent(quad.model),xlab = 'Standardized Residuals')
dev.off()
jpeg("beersales7.jpg")
qqnorm(rstudent(quad.model))
dev.off()

data("winnebago")
jpeg("winnebago.jpg")
plot(winnebago)
abline(-394885.7            ,200.7 )
dev.off()
b=lm(winnebago~time(winnebago))
summary(b)
jpeg("winnebago1.jpg")
plot(rstudent(b))
dev.off()
jpeg("winnebago2.jpg")
plot(log(winnebago))
abline(-984.9388        ,   0.5031 )
dev.off()
c=lm(log(winnebago)~time(winnebago))
jpeg("winnebago3.jpg")
plot(rstudent(c))
dev.off()
logwin.sealm = lm(log(winnebago)~season(winnebago)+time(log(winnebago))-1) 
summary(logwin.sealm) 
jpeg("winnebago4.jpg")
plot(rstudent(logwin.sealm))
dev.off()
runs(rstudent(logwin.sealm))
jpeg("winnebago5.jpg")
acf(rstudent(logwin.sealm))
dev.off()
jpeg("winnebago6.jpg")
hist(rstudent(logwin.sealm),xlab = 'Standardized Residuals')
dev.off()
jpeg("winnebago7.jpg")
qqnorm(rstudent(logwin.sealm))
dev.off()
