present=c(48,38,5,1,1)
absent=c(17066,14464,788,126,37)
total=present+absent
xlev=c(0,0.5,1.5,4.0,7.0)
lin.model.grouped = glm(present/total~xlev, weights = total, family = gaussian) 
summary(lin.model.grouped)
present.new=c(48,38,5,1,0)
total.new=present+absent
lin.model.grouped.new = glm(present.new/total.new~xlev, weights = total.new, family = gaussian) 
summary(lin.model.grouped.new)
xlev.new=c(0,1,2,3,4)
lin.model.grouped.new2 = glm(present/total~xlev.new, weights = total, family = gaussian) 
summary(lin.model.grouped.new2)
log.model.group = glm(cbind(present, absent)~xlev, family = binomial(link = logit)) 
summary(log.model.group)
b=read.table('HorseshoeCrabs.txt',header = T)
lm(b$y~b$weight)
c=glm(b$y~b$weight,family = binomial(link = "logit"))
d=glm(b$y~b$weight,family = binomial(link = 'probit'))