---
title: "Words Regression"
author: "Zhihao ZHAO"
date: "2020/11/30"
output: word_document
---
```{r,warning=F}
setwd("C:/Users/THINKPAD/Desktop/myUW/STAT628 Data Science Practicum/HW3/Data")

review = read.csv("reviews_clean.csv")

num.review<-c()
for(i in c(1:5))
  num.review<-c(num.review,nrow(review[which(review$stars==i),]))
num.review
```


```{r}
word=c('great','nice','friendly','old','the','and',
          'room','service','time','car',
           'desk','staff','place','bed',"manager","food","breakfast",
           "clean","airport","door","floor","bathroom","shower","coffee",
           "pool","towel"
           )
loc=lapply(word,function(x){grep(x,review$text,ignore.case=TRUE)})
names(loc)=word
M=matrix(nrow=5)
for(i in 1:length(loc)){
  M=cbind(M,table(review$stars[loc[[i]]]))
}
M=M[,-1]
colnames(M)<-word
M=M/as.integer(unname(table(review$stars)))


par(mfrow=c(2,3))
for(i in 1:6) barplot(M[,i],col = "lightskyblue",main=names(loc)[i])
par(mfrow=c(2,3))
for(i in 7:12) barplot(M[,i],col = "lightskyblue",main=names(loc)[i])
par(mfrow=c(2,3))
for(i in 13:18) barplot(M[,i],col = "lightskyblue",main=names(loc)[i])
par(mfrow=c(2,4))
for(i in 19:26) barplot(M[,i],col = "lightskyblue",main=names(loc)[i])
```


```{r}
## Correlation part and graphics
stars<-c(1:5)
M.stars<-cbind(stars,M)
stars.frame<-data.frame(M.stars)

corr.words<-c()
for(i in 1:(ncol(M.stars)-1))
  corr.words<-c(corr.words,cor(M.stars[,1],M.stars[,i+1]))#
names(corr.words)<-colnames(M.stars)[-1]
corr.words

library(ggplot2)
r2<-cor(stars.frame$stars, stars.frame$great)
p3<-ggplot(data=stars.frame, aes(x=stars, y=great)) +geom_point()+geom_smooth(method="lm", color="#1a9641") +geom_text(aes(x=3, y=0.3,label=paste("R","=",signif(r2,3),seq="")),color="#fdae61") +theme_bw()
p3

r2<-cor(stars.frame$stars, stars.frame$room)
p3<-ggplot(data=stars.frame, aes(x=stars, y=room)) +geom_point()+geom_smooth(method="lm", color="#1a9641") +geom_text(aes(x=3, y=0.3,label=paste("R","=",signif(r2,3),seq="")),color="#fdae61") +theme_bw()
p3

r2<-cor(stars.frame$stars, stars.frame$old)
p3<-ggplot(data=stars.frame, aes(x=stars, y=old)) +geom_point()+geom_smooth(method="lm", color="#1a9641") +geom_text(aes(x=3, y=0.3,label=paste("R","=",signif(r2,3),seq="")),color="#fdae61") +theme_bw()
p3
```
```{r}
## regression
word=c('great','nice','friendly','old','the','and',
          'room','service','time','car',
           'desk','staff','place','bed',"manager","food","breakfast",
           "clean","airport","door","floor","bathroom","shower","coffee",
           "pool","towel"
           )
loc=lapply(word,function(x){grep(x,review$text,ignore.case=TRUE)})
names(loc)=word

nrow(review)
M.reg<-matrix(0,nrow=nrow(review),ncol=length(word)+1)
M.reg[,1]=review$stars
for(i in 1:length(word)){
  M.reg[loc[[i]],i+1]<-factor(1)
}
colnames(M.reg)<-c("stars",word)

reg.frame<-data.frame(M.reg)
for(i in 2:(length(word)+1))
  reg.frame[[i]]<-as.factor(reg.frame[[i]])
#M.reg[,2:(length(word)+1)]<-

reg<-lm(stars~.,data=reg.frame)
summary(reg)

confint(reg)
```

```{r}
par(mfrow = c(1,2))
qqnorm(rstandard(reg),pch=19,cex=1.2,cex.lab=1.5,cex.main=1,
      main="Normal QQ Plot of the Residuals")
abline(a=0,b=1,col="black",lwd=3)
#A little bit skewed, indicating a light-tail distribution, but not a severe one, so normality is fine 

plot(predict(reg),resid(reg),pch=19,cex=1.2,cex.lab=1.5,cex.main=1,
     xlab="Predicted star ratings", ylab="Standardized Residuals",main="Standardized Residual Plot")
abline(a=0,b=0,col="black",lwd=3)

#plot(M.reg[,1],predict.lm(reg),pch=19,cex=1.2,cex.lab=1.5,cex.main=1.5,
#    xlab="Predicted Body Fat %", ylab="Observed ",main="Fitness test")
#abline(0,1,col="black",lwd=3)
```











